version: "3.3"

services:
  apim-db:
    image: janf57/mysql:0.0.1
    build: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
   
  apacheds:
    image: janf57/apacheds:0.0.1
    build:
      context: apacheds
    container_name: apacheds
    ports:
      - "10389:10389"
      - "10636:10636"
      - "11001:11001"
   
  is-key-manager:
    image: janf57/wso2-is:0.0.1
    build: wso2-is
    container_name: is
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
    volumes:
      - wso2data:/usr/share/wso2/data
    depends_on:
      - apim-db
      - apacheds
  
  api-manager:
    image: janf57/wso2-am:0.0.1
    build: wso2-am
    container_name: am
    ports:
      - "9444:9444"
      - "9764:9764"
      - "8244:8244"
      - "8281:8281"
    volumes:
      - wso2data:/usr/share/wso2/data  
    depends_on:
      - apim-db
      - apacheds
      - is-key-manager
      
      
volumes:
  wso2data:
    driver: local