version: "3.3"

services:
  mysql-apacheds:
    image: mysql-apacheds
    container_name: sql-ldap
    environment:
      - MYSQL_ROOT_PASSWORD=wso2
    ports:
      - "3306:3306"
      - "10389:10389"
      - "10636:10636"
      - "11001:11001"
   
  is-key-manager:
    image: wso2-is
    container_name: is
    ports:
      - "9443:9443"
      - "9763:9763"
      - "8243:8243"
      - "8280:8280"
    volumes:
      - wso2data:/usr/share/wso2/data
    depends_on:
      - mysql-apacheds
  
  api-manager:
    image: wso2-am
    container_name: am
    ports:
      - "9444:9443"
      - "9764:9763"
      - "8244:8243"
      - "8281:8280"
    volumes:
      - wso2data:/usr/share/wso2/data  
    depends_on:
      - mysql-apacheds
      - wso2is
      
      
volumes:
  wso2data:
    driver: local